### ISSUE TITLE
Please decipher the code.

### ISSUE THREAD

**Issue by uniyalnitin** [bitmazk/django-payslip#1]
I'm not able to understand how you have added functionality that allows users to create new attributes to a model from admin panel. Can you please elaborate??

**Comment by Tyrdall** [comment]
@uniyalnitin Please be more specific. This app doesn't contain any magic code ;)

**Comment by uniyalnitin** [comment]
You are allowing users to create attributes for a model, you are using
ExtaField and ExtraFieldType classes, but newly created attributes aren't
displayed for the main model (for which I want to create the attributes in
admin panel)

**Comment by simkimsia** [comment]
@Tyrdall I have a similar question as @uniyalnitin

**Comment by Tyrdall** [comment]
If you create an extra field type for the model "Employee", for instance, then create an extra field using that field type, it will appear in the many2many of the Employee model.

If that doesn't work please try to exactly explain what you are trying to do, what you expect and what actually happens.

**Comment by simkimsia** [comment]
Thanks for the explanation!

It helped me :)

KimSia kimsia@oppoin.com https://simkimsia.com ( https://simkimsia.com/ )

P.S. What I'm doing now: https://simkimsia.com/now

**Comment by Tyrdall** [comment]
Great :)
